# Code from https://rust-unofficial.github.io/too-many-lists/

[package]
name = "too-many-lists"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
